### ISSUE TITLE
Alice Baird, Emily Chen, Sang-Hee Min Project

### ISSUE THREAD

**Issue by aliceebaird** [Ecohen4/data-viz#173]
<b> Alice Baird, Emily Chen, Sang-Hee Min </b> 

Here is the link to our project repository. 
https://github.com/aliceebaird/six5532one-koala-pop

<i> inside we have all data and rmd of data crunch. </i> 
Heres the link to the io so you can view it. 
http://aliceebaird.github.io/six5532one-koala-pop/index.html

If you could inform us once you have it we will be able to remove it from this public repository. The quicker we can do that the better. 

Kindest

Alice

**Comment by Ecohen4** [comment]
Graded. You may take it down as you see fit.

Have a great summer!
Elliot
